### ISSUE TITLE
unity 2019.3 missing Unity.Networking

### ISSUE THREAD

**Issue by soraphis** [TeamSirenix/odin-serializer#30]
```
Assembly 'Assets/Plugins/Sirenix/Odin Serializer/EditorOnly/OdinSerializer.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEngine.Networking'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Using 2019.3.0b3 on Linux (Ubuntu)

**Comment by Prontsevich** [comment]
I have the same error on Unity 2019.2.3f1 on Windows

**Comment by TorVestergaard** [comment]
This issue has been resolved for a long while, though the out of date releases have not reflected this. The new and far less tedious release system is now in place, so I'm closing this issue.

**Comment by KiraTile** [comment]
Hello. Its not resolved 
![image](https://user-images.githubusercontent.com/48332697/77855788-5a10c580-71fb-11ea-9e7a-4bad91202455.png)
this is unity 2019.3.7f1
Happened after upgrading project.

**Comment by TorVestergaard** [comment]
Hmm, perhaps the very, very old pre-built .dll's have not reflected. All you have to do is recompile the solution. Meanwhile, I'll push a commit with some newly built .dll's. That should take care of the issue :)
